[package]
name = "message-to-csv-discordbot"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
dotenv = "0.15.0"
poise = "0.6.1"
serde = "1.0.217"
serde_derive = "1.0.217"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
